const a = {
  disableHostCheck: true,
  compress: true,
  clientLogLevel: 'none',
  contentBase: 'D:\\Project\\git-mine\\react-ts-antd\\public',
  contentBasePublicPath: '/',
  watchContentBase: true,
  hot: true,
  transportMode: 'ws',
  injectClient: false,
  publicPath: '',
  quiet: true,
  watchOptions: { ignored: {} },
  https: false,
  host: '0.0.0.0',
  overlay: false,
  historyApiFallback: { disableDotRule: true, index: '/' },
  public: '192.168.204.1',
};
